version: '3'
services:
  mongodb:
    image: mongo
    hostname: mongo
    volumes:
      - /mongodata:/data/db
    ports:
      - "27017:27017"
  randomearth:
    build: ./src/terra/randomEarth
    depends_on:
      - mongodb
    environment:
      - WAIT_HOSTS=mongodb:27017
    volumes:
      - ./:/home/clement/rpiBots