version: '3'
services:
  mongodb:
    image: mongo:4.0-xenial
    hostname: mongo
    ports:
      - "27017:27017"
  randomearth:
    build: ./src/terra/randomEarth
    ports:
      - "80"

volumes:
  mongo-data: